/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/**
    1. RCC (Reset Clock and Control)
    base address: 0x40023800 
    ABH1 Peripheral clock enabler regester offset: 0x30
*/
#define RCC_AHB1ENR (*(volatile uint32_t *)(0x40023800 + 0x30))

#define GPIOD_BASE (0x40020C00)

/*
    2. GPIOD Base address: 0x40020C00
    GPIO Port mode register offset: 0x00
*/
#define GPIOD_MODER (*(volatile uint32_t *)(GPIOD_BASE + 0x00))

/**
    3. GPIO port output data register
    address offset: 0x14
*/

#define GPIOD_ODR (*(volatile uint32_t *)(GPIOD_BASE + 0x14))

int main(void){

    // Enable the clock for GPIOD
    RCC_AHB1ENR |= (1<<3);

    // Step 1 make pin 12 bits 24 and 25 00 
    GPIOD_MODER &= ~(3<<24);

    // step 2 change the moder from 00 to 01
    GPIOD_MODER |= (1<<24);

    while(1){
        GPIOD_ODR ^= (1<<12);

        for(volatile uint32_t i=0; i<5000000; i++){
            
        }
    }
}
